coverage:
  range: 70..90
  status:
    project:
      default:
        target: auto
        threshold: 5%

fixes:
  - "/home/runner/work/gpjax/gpjax/::" # Correct paths

ignore:
  - "setup.py"
  - "*/tests/.*"
  - "tests/kernels/*.py"
  - "__init__.py"
  - "tests/*.py"
  - "**/_version.py"
  - "**/versioneer.py"
  - "versioneer.py"
