comment: false

coverage:
  status:
    project:
      default:
        target: "97"
    patch:
      default:
        target: "100"

ignore:
  - "setup.py"
  - "*/tests/.*"
  - "__init__.py"
  - "tests/*.py"
  - "**/_version.py"
  - "**/versioneer.py"
  - "versioneer.py"