---
blank_issues_enabled: false
contact_links:
  - name: JaxKern Community Support
    url: https://github.com/JaxGaussianProcesses/JaxKern/discussions
    about: Please ask and answer questions here.
