---
blank_issues_enabled: false
contact_links:
  - name: JaxLinOp Community Support
    url: https://github.com/JaxGaussianProcesses/JaxLinOp/discussions
    about: Please ask and answer questions here.
