name: Benchmarks

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run-benchmarks:
    name: Run benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.4.0

      # Configure Poetry to use the virtual environment in the project
      - name: Setup Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install --all-extras --with dev
          pip install virtualenv

      - name: Set asv machine
        run: asv machine --yes

      - name: Run benchmarks
        run: |
          cd benchmarks
          asv run --python PYTHON
          asv publish

      - name: Deploy to benchmarks branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.asv/html
          publish_branch: benchmarks
